import spacy
import numpy as np
from lemminflect import getInflection

nlp = spacy.load("en_core_web_md")

with open("common_ambiguous_phrases.txt", "r") as f:
    ambiguous_vo = [line.strip() for line in f if line.strip()]

# splitting the ambiguous verb object pairs from the txt file
ambiguous_vo_tokens = []
for vo in ambiguous_vo:
    parts = vo.split()
    if len(parts) == 2:
        verb_tok = nlp(parts[0])[0]
        obj_tok  = nlp(parts[1])[0]
        ambiguous_vo_tokens.append((verb_tok, obj_tok))

# I set a small list of ambiguous subjects
ambiguous_subjects = ["someone", "people", "they", "the group", "he", "she", "it"]
ambiguous_subject_tokens = [nlp(s)[0] for s in ambiguous_subjects]

print("\n--- Enter Sentence A ---")
user_input_a = input("Sentence A: ").strip().rstrip(".")
doc_a = nlp(user_input_a)

print("\n--- Enter Sentence B ---")
user_input = input("Sentence B: ").strip().rstrip(".")
doc_b = nlp(user_input)

def extract_svo(doc):
    subj = verb = obj = None
    for token in doc:
        if subj is None and token.pos_ in {"NOUN", "PRON"}:
            subj = token
        elif verb is None and token.pos_ == "VERB":
            verb = token
        elif obj is None and token.pos_ in {"NOUN", "PRON"} and token != subj:
            obj = token
    return subj, verb, obj

svo_a = extract_svo(doc_a)
svo_b = extract_svo(doc_b)

print("Sentence A SVO:", tuple(t.text if t else None for t in svo_a))
print("Sentence B SVO:", tuple(t.text if t else None for t in svo_b))
def avg_similarity(tokens_to_check, reference_tokens):
    sims = []
    for t in tokens_to_check:
        for r in reference_tokens:
            sims.append(t.similarity(r))
    return np.mean(sims) if sims else -1

# Picks the best subject
best_subj = max(
    ambiguous_subject_tokens,
    key=lambda s: avg_similarity([s], [svo_a[0], svo_b[0]])
)

# Picks the best VO pair
best_vo = max(
    ambiguous_vo_tokens,
    key=lambda vo: avg_similarity([vo[0], vo[1]], [svo_a[1], svo_a[2], svo_b[1], svo_b[2]])
)

# Assemble sentence with correct verb inflection. This part of the code was generated by ChatGPT.
def assemble_sentence(subj_token, vo_tokens):
    verb_tok = vo_tokens[0]
    obj_tok  = vo_tokens[1]

    # Use lemminflect to get correct verb form
    if subj_token.tag_ in {"NNS", "NNPS"}:
        verb_text = getInflection(verb_tok.text, tag="VB")[0] if getInflection(verb_tok.text, tag="VB") else verb_tok.text
    else:
        verb_text = getInflection(verb_tok.text, tag="VBZ")[0] if getInflection(verb_tok.text, tag="VBZ") else verb_tok.text

    return f"{subj_token.text.capitalize()} {verb_text} {obj_tok.text}."

third_sentence = assemble_sentence(best_subj, best_vo)


print("\n--- Generated Third Sentence ---")
print(third_sentence)


